name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@netail'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Publish
        uses: changesets/action@v1
        with:
          version: yarn changeset:version
          publish: yarn changeset:publish
          title: 'New release'
          commit: 'chore: release version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
